name: Build and Run docker container
 
# Ejecutar el workflow en cada push a la rama main
on:
  push:
    branches:
      - main
      - LS-dev

jobs:
  build:
    # El trabajo se ejecutar치 en una m치quina virtual de Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Checkout del c칩digo del repositorio
    - name: Check out the repository
      uses: actions/checkout@v4

    # Autenticarse en Docker Hub (opcional, si necesitas subir la imagen)
    # Para esto, es necesario configurar Docker Hub username y password como secrets
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Construir la imagen Docker utilizando el Dockerfile
    - name: Build Docker image
      run: docker build -t clases_udem:latest .

    # (Opcional) Etiquetar la imagen con el hash del commit
    - name: Tag Docker image with commit hash
      run: docker tag clases_udem:latest moncho30/github_actions:${{ github.sha }}

    # (Opcional) Subir la imagen a Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push moncho30/github_actions:${{ github.sha }}

    # Ejecutar el contenedor a partir de la imagen Docker
    - name: Run Docker container
      run: docker run -i --name c_clases_udem clases_udem:latest

    # (Opcional) Verificar si el contenedor est치 corriendo correctamente
    - name: Verify Docker container is running
      run: docker ps
